{"uuid":"fe21dc4e-30e5-447d-ab3e-23b70590f428","historyId":"f46ab70fd9bb087d94ed3b3d70d7e3f6","fullName":"org.example.NegativeAuthTests.testGetUserInfoWithoutAuthorization","labels":[{"name":"package","value":"org.example.NegativeAuthTests"},{"name":"testClass","value":"org.example.NegativeAuthTests"},{"name":"testMethod","value":"testGetUserInfoWithoutAuthorization"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"REST"},{"name":"subSuite","value":"org.example.NegativeAuthTests"},{"name":"host","value":"DESKTOP-3LF89KH"},{"name":"thread","value":"11108@DESKTOP-3LF89KH.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Получение информации о пользователе"},{"name":"epic","value":"Негативное тестирование управления пользователями и новостями"}],"links":[],"name":"testGetUserInfoWithoutAuthorization","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Error message is incorrect expected [Unauthorized] but found [null]","trace":"java.lang.AssertionError: Error message is incorrect expected [Unauthorized] but found [null]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:629)\r\n\tat org.example.NegativeAuthTests.testGetUserInfoWithoutAuthorization(NegativeAuthTests.java:65)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify user cannot get user info without authorization","steps":[],"attachments":[],"parameters":[],"start":1725383055908,"stop":1725383056544}